language: scala

scala:
  - "2.12.8"

jdk:
  - oraclejdk8
  - oraclejdk9

sudo: false

notifications:
  email:
    recipients:
      - marko.elezovic@oradian.com

script:
  # Try to build documentation, package sources and run tests
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal test
