language: scala

scala:
  - "2.13.3"

jdk:
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8

sudo: false

notifications:
  email:
    recipients:
      - marko.elezovic@oradian.com

script:
  # Try to build documentation, package sources and run tests
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal jacoco
