dist: xenial

sudo: false

branches:
  only:
  - master

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.cache/coursier/v1

language: scala

scala:
  - "2.13.3"

jdk:
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8

notifications:
  email:
    recipients:
      - marko.elezovic@oradian.com

script:
  # Try to build documentation, package sources and run tests
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal clean jacoco

after_success:
  - bash <(curl -s https://codecov.io/bash)
